apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

resources:
- api-gateway-ingress.yaml
- edge-service-rollout.yaml

namespace: polarbook-development

patches:
- patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
       name: edge-service-rollout
      spec:
        template:
          spec:
            containers:
              - name: edge-service-container
                env:
                  - name: SPRING_PROFILES_ACTIVE
                    value: production
                  - name: JAVA_TOOL_OPTIONS
                    value: -javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.6.0.jar
                  - name: OTEL_SERVICE_NAME
                    value: edge-service           
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: http://tempo.polarbook-monitoring.svc.cluster.local:4318
                  - name: OTEL_METRICS_EXPORTER
                    value: none
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
     name: edge-service-rollout
    spec:
      replicas: 3

images:
- name: ghcr.io/upen28/polar-bookshop/edge-service
  newName: ghcr.io/upen28/polar-bookshop/edge-service/dev
  newTag: 2c18595ead21361948ca31f5e346108ba641a69f

configMapGenerator:
  - name: edge-configmap
    files:
      - application.yaml
    options:
      labels:
        app: edge-service